ALLComplex/Cultivate

- app/src/main/java/com/cultivate/juniordesign/cultivate/MainActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/StubActivity.java
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_stub.xml
stub page stuff. Doesn't actually attempt to  go to stub page, but it does show snack bar though.
> Slowly adding stub page functionality

- app/src/main/java/com/cultivate/juniordesign/cultivate/GroupActivity.java
> Adds a whitespace to get rid of a bug

- app/src/main/java/com/cultivate/juniordesign/cultivate/EventActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/GroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/MainActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/StubActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_stub.xml
- app/src/main/res/layout/event_stub.xml
- app/src/main/res/layout/group_stub.xml
- app/src/main/res/layout/hamburgerbar_popup.xml
- app/src/main/res/layout/information_popup.xml
- app/src/main/res/layout/profile_stub.xml
Adds the hamburger bar with minimal functionality at every view.
> Adds Hamburger Bar

- app/src/main/java/com/cultivate/juniordesign/cultivate/GroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/MainActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/StubActivity.java
- app/src/main/res/layout/hamburgerbar_popup.xml
updates the appearence of the hamburger bar
> Appearence

- app/src/main/java/com/cultivate/juniordesign/cultivate/EventActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/GroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/StubActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/hamburgerbar_popup.xml
Incorporates the log out functionality in to the hamburger bar
> Incorporating log out functionality in hamburger bar

- app/src/main/java/com/cultivate/juniordesign/cultivate/GroupActivity.java
Just comments out code that doesn't function right
> Fix to Bug

- app/src/main/java/com/cultivate/juniordesign/cultivate/Account.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/CreateGroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/EventActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/Group.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/GroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/JoinGroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/MainActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/RegistrationActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/StubActivity.java
Replaced args and made the intent user extraction consistent across all
the activities
> Fixing groups

- app/src/main/java/com/cultivate/juniordesign/cultivate/FirebaseHandler.java
Firebase handler to be called from activities that will allow easy
reads and writes of full objects to database
> Added firebase handler

- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/GroupProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/JoinGroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/FirebaseHandler.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/GetDataListener.java
- app/src/main/res/layout/activity_group_profile.xml
- app/src/main/res/layout/join_group_layout.xml
Can successfully join groups. Current behaviour after joining a group is
to go to the My Groups page. Redid firebase stuff to successfully add
and remove from groups.
> Groups: Joining

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/CreateGroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/GroupListActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/GroupProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/HamburgerActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/MyGroupsActivity.java
- app/src/main/res/layout/activity_group_profile.xml
- app/src/main/res/layout/create_group_layout.xml
finished group creation details
> Group creation stuff

- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/CreateGroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/EventActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/GroupListActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/GroupProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/HamburgerActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/JoinGroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/MainActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/MyGroupsActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/ProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/StubActivity.java
- app/src/main/res/layout/activity_group_list.xml
- app/src/main/res/layout/activity_group_profile.xml
- app/src/main/res/layout/activity_my_groups.xml
- app/src/main/res/layout/profile_stub.xml
Needed to pass in page-specific layout info to the haburgerbar method, the lack of which caused the app to crash if the HBB opened on a page that wasn't main
> HamburgerBarBug - only opened on main page

- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/GroupProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/JoinGroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/MyGroupsActivity.java
- app/src/main/res/layout/activity_group_profile.xml
- app/src/main/res/layout/activity_my_groups.xml
Creates buttons for each group you are a part of on the my groups page onClick goes to their profile. 
Still has formatting issues for UI appearance. Other minor changes to keep formatting more clean and clear for future
> Layouts sprint3

- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/ProfileActivity.java
- app/src/main/res/layout/activity_my_profile.xml
you can now edit a persons name. A persons email is shown.
> Added stuff to the profile screen

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/CreateGroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/GroupProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/JoinGroupActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/MembersListActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/MyGroupsActivity.java
- app/src/main/res/layout/activity_group_profile.xml
- app/src/main/res/layout/activity_member_list.xml
also adds some toasts where needed and missing standard methods on group profile page
also adds member list screen that admins can view by going to group profile
> Fixes a few join group bugs

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/cultivate/juniordesign/cultivate/Account.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/CreateEventActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/EventActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/GroupProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/Event.java
- app/src/main/res/layout/activity_create_event.xml
- app/src/main/res/layout/activity_group_profile.xml
Added support for the creation of events, as well as users marking themselves as attending and not attending. NOTE: This breaks the main page's "event" button.
> Add event support

- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/GroupProfileActivity.java
- app/src/main/res/layout/activity_group_profile.xml
Made group events look like buttons. Need event adding/joining
funcitonality for them to do stuff. Currently has dummy functionality on
click.
> Make Group Events look like Buttons

- app/src/main/java/com/cultivate/juniordesign/cultivate/Account.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/GroupProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/Group.java
Added admin resign functionality with confirmation popup and made sure that at least one admin remained in each group. Also made sure no gradle issues occurred this time.
> added admin resign functionality without breaking gradle

- app/src/main/java/com/cultivate/juniordesign/cultivate/Account.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/CreateEventActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/EventActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/GroupProfileActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/Event.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/Utility.java
- app/src/main/res/layout/activity_create_event.xml
Event times now display. So yay there.
> Event dateTime changes

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/AttendanceActivity.java
- app/src/main/java/com/cultivate/juniordesign/cultivate/ActivityClass/EventActivity.java
- app/src/main/res/layout/activity_attendance.xml
> Attendance page

- README.md
Added Release notes for Cultivate 1.0
> Customer Delivery Documents
